# Generated by Django 3.1.7 on 2021-09-24 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='input_data',
            old_name='data',
            new_name='input_values',
        ),
    ]
